#!/usr/bin/env python3
"""Generate module documentation from registry/modules.yaml.

Generated:
  docs/modules/<id>.md          one page per module
  docs/modules/README.md        index + gate matrix
  docs/03-dependency-dag.md     graph section between markers
  README.md                     status matrix between markers

Hand-written prose lives in docs/*.md. Anything derived from the registry is
generated, so the registry can never disagree with the docs. Run:

    make docs        # regenerate
    make docs-check  # fail if the tree is stale (CI runs this)
"""
from __future__ import annotations

import pathlib
import sys

from _registry import ROOT, load_gates, load_registry, modules_by_id, topo_sort

DOCS = ROOT / "docs"
MODDOCS = DOCS / "modules"
BANNER = "<!-- GENERATED BY scripts/gen_docs.py — DO NOT EDIT BY HAND -->"


def bullets(items, empty="_none declared_") -> str:
    items = items or []
    if not items:
        return empty
    return "\n".join(f"- {i}" for i in items)


def gate_row(m, all_gates) -> str:
    req = set(m.get("required_gates") or [])
    cells = "".join(f" {'●' if g in req else '·'} |" for g in all_gates)
    return f"| `{m['id']}` |{cells}"


def render_module(m, mods, gates_doc, dependents) -> str:
    all_gates = list(gates_doc["gates"])
    req = m.get("required_gates") or []
    deps = m.get("depends_on") or []
    slo = m.get("slo")

    dep_lines = "\n".join(
        f"- [`{d}`]({d}.md) — {mods[d]['name']}" for d in deps
    ) or "_none — this module is a root of the DAG._"
    used_by = "\n".join(
        f"- [`{d}`]({d}.md) — {mods[d]['name']}" for d in sorted(dependents.get(m["id"], []))
    ) or "_nothing depends on this module yet._"

    gate_table = "\n".join(
        f"| {g} | {gates_doc['gates'][g]['name']} | {'**required**' if g in req else 'not required'} |"
        for g in all_gates
        if gates_doc["gates"][g]["stage"] == "ci"
    )

    slo_block = ""
    if slo:
        slo_block = (
            "\n## Service level objectives\n\n"
            f"{slo.get('note','')}\n\n"
            + bullets(slo.get("metrics"))
            + "\n"
        )

    return f"""{BANNER}

# `{m['id']}` — {m['name']}

| | |
|---|---|
| **Tier** | {m['tier']} |
| **Status** | `{m['status']}` |
| **Release approval** | {m['release_approval']} |
| **Required gates** | {' '.join(f'`{g}`' for g in req)} |

## Purpose

{m['purpose'].strip()}

## Depends on

{dep_lines}

## Depended on by

{used_by}

## Inputs

{bullets(m.get('inputs'))}

## Outputs

{bullets(m.get('outputs'))}

## What gets built

{bullets(m.get('builds'))}

## Invariants

These are executed as tests at gate **G4**. A module may not declare an
invariant it does not test.

{bullets(m.get('invariants'))}

## Test obligations

{bullets(m.get('tests'))}

## Known failure modes

The things that go wrong in systems like this one. Each should map to a test above.

{bullets(m.get('failure_modes'))}
{slo_block}
## Gate matrix

| Gate | Name | This module |
|---|---|---|
{gate_table}

{('## Notes\n\n' + m['notes'].strip() + '\n') if m.get('notes') else ''}
---

_Generated from [`registry/modules.yaml`](../../registry/modules.yaml). Edit the registry, then run `make docs`._
"""


def render_index(order, mods, gates_doc, registry) -> str:
    all_gates = [g for g in gates_doc["gates"] if gates_doc["gates"][g]["stage"] == "ci"]
    header = "| Module |" + "".join(f" {g} |" for g in all_gates)
    sep = "|---|" + "---|" * len(all_gates)
    rows = "\n".join(gate_row(mods[mid], all_gates) for mid in order)

    tier_sections = []
    for tier, meta in registry["tiers"].items():
        members = [mid for mid in order if mods[mid]["tier"] == tier]
        if not members:
            continue
        lines = "\n".join(
            f"- [`{mid}`]({mid}.md) — {mods[mid]['name']} · `{mods[mid]['status']}`"
            for mid in members
        )
        tier_sections.append(
            f"### {tier} — {meta['name']}\n\n"
            f"_Blast radius: {meta['blast_radius']}._\n"
            f"_Change policy: {meta['change_policy']}._\n\n{lines}\n"
        )

    return f"""{BANNER}

# Module index

{len(order)} modules, listed in dependency (build) order. A module may not be
started before every module above it that it depends on has passed its gates.

## By tier

{chr(10).join(tier_sections)}

## Build order

{chr(10).join(f'{i}. [`{mid}`]({mid}.md)' for i, mid in enumerate(order, 1))}

## Required-gate matrix

`●` required · `·` not required

{header}
{sep}
{rows}

---

_Generated from [`registry/modules.yaml`](../../registry/modules.yaml). Edit the registry, then run `make docs`._
"""


def render_mermaid(order, mods) -> str:
    lines = ["```mermaid", "graph TD"]
    tier_class = {"T0": "core", "T1": "market", "T2": "finops", "T3": "compliance", "T4": "edge"}
    for mid in order:
        m = mods[mid]
        label = m["name"].replace('"', "'")
        lines.append(f'  {mid.replace("-", "_")}["{mid}<br/>{label}"]:::{tier_class[m["tier"]]}')
    for mid in order:
        for dep in mods[mid].get("depends_on") or []:
            lines.append(f'  {dep.replace("-", "_")} --> {mid.replace("-", "_")}')
    lines += [
        "  classDef core fill:#7f1d1d,stroke:#fca5a5,color:#fff;",
        "  classDef market fill:#1e3a8a,stroke:#93c5fd,color:#fff;",
        "  classDef finops fill:#065f46,stroke:#6ee7b7,color:#fff;",
        "  classDef compliance fill:#78350f,stroke:#fcd34d,color:#fff;",
        "  classDef edge fill:#3730a3,stroke:#a5b4fc,color:#fff;",
        "```",
    ]
    return "\n".join(lines)


def render_invariants(order, mods) -> str:
    lines = []
    for mid in order:
        m = mods[mid]
        inv = m.get("invariants") or []
        if not inv:
            continue
        lines.append(f"### `{mid}` — {m['name']}\n")
        lines.append(f"_Gated at G4. Tier {m['tier']}._\n")
        for item in inv:
            text = str(item)
            if ":" in text and text.split(":", 1)[0].strip().startswith("INV-"):
                tag, body = text.split(":", 1)
                lines.append(f"- **{tag.strip()}** — {body.strip()}")
            else:
                lines.append(f"- {text}")
        lines.append("")
    return "\n".join(lines)


def render_status_matrix(order, mods) -> str:
    rows = "\n".join(
        f"| {i} | [`{mid}`](docs/modules/{mid}.md) | {mods[mid]['tier']} | "
        f"{mods[mid]['name']} | `{mods[mid]['status']}` | "
        f"{' '.join(mods[mid].get('required_gates') or [])} |"
        for i, mid in enumerate(order, 1)
    )
    return (
        "| # | Module | Tier | Name | Status | Required gates |\n"
        "|---|---|---|---|---|---|\n" + rows
    )


def replace_block(path: pathlib.Path, marker: str, content: str) -> bool:
    start = f"<!-- BEGIN:{marker} -->"
    end = f"<!-- END:{marker} -->"
    text = path.read_text()
    if start not in text or end not in text:
        print(f"warning: markers {marker} not found in {path}", file=sys.stderr)
        return False
    pre = text.split(start)[0]
    post = text.split(end)[1]
    new = f"{pre}{start}\n{content}\n{end}{post}"
    if new != text:
        path.write_text(new)
        return True
    return False


def main(argv: list[str]) -> int:
    check = "--check" in argv
    registry = load_registry()
    gates_doc = load_gates()
    mods = modules_by_id(registry)
    order = topo_sort(mods)

    dependents: dict[str, set[str]] = {k: set() for k in mods}
    for mid, m in mods.items():
        for dep in m.get("depends_on") or []:
            dependents[dep].add(mid)

    MODDOCS.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    def emit(path: pathlib.Path, content: str):
        if path.exists() and path.read_text() == content:
            return
        if check:
            written.append(str(path.relative_to(ROOT)))
            return
        path.write_text(content)
        written.append(str(path.relative_to(ROOT)))

    for mid in order:
        emit(MODDOCS / f"{mid}.md", render_module(mods[mid], mods, gates_doc, dependents))
    emit(MODDOCS / "README.md", render_index(order, mods, gates_doc, registry))

    dag_doc = DOCS / "03-dependency-dag.md"
    if dag_doc.exists():
        block = render_mermaid(order, mods) + "\n\n### Build order\n\n" + "\n".join(
            f"{i}. `{mid}` — {mods[mid]['name']}" for i, mid in enumerate(order, 1)
        )
        if replace_block(dag_doc, "DAG", block):
            written.append(str(dag_doc.relative_to(ROOT)))

    inv_doc = DOCS / "05-invariants.md"
    if inv_doc.exists():
        if replace_block(inv_doc, "INVARIANTS", render_invariants(order, mods)):
            written.append(str(inv_doc.relative_to(ROOT)))

    readme = ROOT / "README.md"
    if readme.exists():
        if replace_block(readme, "STATUS", render_status_matrix(order, mods)):
            written.append("README.md")

    if check and written:
        print("Documentation is stale. Run `make docs`. Affected:", file=sys.stderr)
        for w in written:
            print(f"  - {w}", file=sys.stderr)
        return 1
    print(f"docs: {len(written)} file(s) {'stale' if check else 'written'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
